# Generated by Django 3.0.6 on 2020-05-10 15:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='狼性书生', max_length=20, verbose_name='博主名')),
                ('head_photo', models.ImageField(blank=True, default='/cover_img/default.jpg', null=True, upload_to='blog_img', verbose_name='头像')),
                ('blog_major', models.CharField(default='程序猿', max_length=20, verbose_name='职业')),
                ('autograph', ckeditor.fields.RichTextField(default='个性签名', verbose_name='个性签名')),
                ('blog_email', models.EmailField(default='794859685@qq.com', max_length=254, verbose_name='博主邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(default='/layout_img/favicon.ico', upload_to='layout_img', verbose_name='Logo')),
                ('website_name', models.CharField(default='Mr Wolf Blog', max_length=10, verbose_name='网站标题名')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=50, verbose_name='链接')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogger_link', to='blogger.Blogger')),
            ],
        ),
    ]
