# Generated by Django 3.0.6 on 2020-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon_name',
            field=models.CharField(default='fa fa-dribbble', max_length=50, verbose_name='链接图标'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='website_name',
            field=models.CharField(default='Mr Wolf Blog', max_length=20, verbose_name='网站标题名'),
        ),
    ]
